### PR TITLE
Fix test failures currently on master (but not showing because of old Travis builds)

### PR DESCRIPTION
**Pull request by wwalser**
The last Travis builds were 4 months ago so my PR failed when the actual trouble is on upstream master.

Fixed…

### CODE REVIEW

**Comment by jaredhanson** [comment]
Fixed by #8ca5e55

**Comment by jaredhanson** [comment]
In what case would you choose to use `https://www.googleapis.com/userinfo/v2/me` over `https://www.googleapis.com/oauth2/v3/userinfo`?

The latter is the one advertised in Google's OpenID Connect configuration [document](https://accounts.google.com/.well-known/openid-configuration).  I can't find any documentation on using the /userinfo/v2/me endpoint, and if its not needed, I don't want to make it easier to use this strategy with undocumented endpoints.

**Comment by wwalser** [comment]
@jaredhanson did you mean to post that question over here: https://github.com/jaredhanson/passport-google-oauth2/pull/8?

If so, I believe my answer in this thread: https://github.com/jaredhanson/passport-google-oauth2/issues/7 is relevant. 

To be honest it's been so long since I've looked into this that I don't remember all of the details. From what I can remember I wanted to avoid Google+ APIs all together and at the time that URL was the documented way to go about it.

**Comment by jaredhanson** [comment]
> @jaredhanson did you mean to post that question in #8?

Yes, sorry.  Typed into the wrong tab :)

It seems like #8 isn't really necessary anymore, because the latest recommendation from google has /userinfo at the end of the URL right?   I like the more strict check, and the latest passes that strict check, so no need to merge #8?

**Comment by wwalser** [comment]
Again, it's been so long I don't remember. I ended up using https://developers.google.com/identity/sign-in/web/ as I felt it provided a better user experience. I had it all in my head when I opened these two PRs and a few against Bell and other projects six months ago.

Feel free to close. It seemed like the URLs had changed as Google moved away from Plus but I don't know the state of things today.

**Pull request closed without merging**
